export const tableHeaders = [
  "Route Name",
  "No of Bus Stops",
  "Assigned Buses",
  "Start Location",
  "Destination Point",
];

export const tableData = [
  {
    id: 1,
    routeName: "Remera - Downtown",
    routeLength: "5km",
    routeCode: "REM - DOWN",
    busStopsCount: 3,
    assignedBuses: 10,
    startLoc: 6.0,
    destLoc: 24,
    busStops: [
      { id: 1, name: "City Plaza", lat: -1, long: 30 },
      { id: 2, name: "Camp Kigali", lat: -1, long: 30 },
      { id: 3, name: "Kimironko", lat: -1, long: 30 },
    ],
  },
  {
    id: 2,
    routeName: "Remera - Downtown",
    routeLength: "5km",
    routeCode: "REM - DOWN",
    busStopsCount: 3,
    assignedBuses: 10,
    startLoc: 6.0,
    destLoc: 24,
    busStops: [
      { id: 1, name: "City Plaza", lat: -1, long: 30 },
      { id: 2, name: "Camp Kigali", lat: -1, long: 30 },
      { id: 3, name: "Kimironko", lat: -1, long: 30 },
    ],
  },
  {
    id: 3,
    routeName: "Remera - Downtown",
    routeLength: "5km",
    routeCode: "REM - DOWN",
    busStopsCount: 3,
    assignedBuses: 10,
    startLoc: 6.0,
    destLoc: 24,
    busStops: [
      { id: 1, name: "City Plaza", lat: -1, long: 30 },
      { id: 2, name: "Camp Kigali", lat: -1, long: 30 },
      { id: 3, name: "Kimironko", lat: -1, long: 30 },
    ],
  },
  {
    id: 4,
    routeName: "Remera - Downtown",
    routeLength: "5km",
    routeCode: "REM - DOWN",
    busStopsCount: 3,
    assignedBuses: 10,
    startLoc: 6.0,
    destLoc: 24,
    busStops: [
      { id: 1, name: "City Plaza", lat: -1, long: 30 },
      { id: 2, name: "Camp Kigali", lat: -1, long: 30 },
      { id: 3, name: "Kimironko", lat: -1, long: 30 },
    ],
  },
  {
    id: 5,
    routeName: "Gikondo - Town",
    routeLength: "5km",
    routeCode: "REM - DOWN",
    busStopsCount: 3,
    assignedBuses: 10,
    startLoc: 6.0,
    destLoc: 24,
    busStops: [
      { id: 1, name: "City Plaza", lat: -1, long: 30 },
      { id: 2, name: "Camp Kigali", lat: -1, long: 30 },
      { id: 3, name: "Kimironko", lat: -1, long: 30 },
    ],
  },
  {
    id: 6,
    routeName: "Remera - Downtown",
    routeLength: "5km",
    routeCode: "REM - DOWN",
    busStopsCount: 3,
    assignedBuses: 10,
    startLoc: 6.0,
    destLoc: 24,
    busStops: [
      { id: 1, name: "City Plaza", lat: -1, long: 30 },
      { id: 2, name: "Camp Kigali", lat: -1, long: 30 },
      { id: 3, name: "Kimironko", lat: -1, long: 30 },
    ],
  },
  {
    id: 7,
    routeName: "Nyabugogo - Kacyiru",
    routeLength: "5km",
    routeCode: "REM - DOWN",
    busStopsCount: 3,
    assignedBuses: 10,
    startLoc: 6.0,
    destLoc: 24,
    busStops: [
      { id: 1, name: "City Plaza", lat: -1, long: 30 },
      { id: 2, name: "Camp Kigali", lat: -1, long: 30 },
      { id: 3, name: "Kimironko", lat: -1, long: 30 },
    ],
  },
  {
    id: 8,
    routeName: "Nyabugogo - Downtown",
    routeLength: "5km",
    routeCode: "REM - DOWN",
    busStopsCount: 3,
    assignedBuses: 10,
    startLoc: 6.0,
    destLoc: 24,
    busStops: [
      { id: 1, name: "City Plaza", lat: -1, long: 30 },
      { id: 2, name: "Camp Kigali", lat: -1, long: 30 },
      { id: 3, name: "Kimironko", lat: -1, long: 30 },
    ],
  },
  {
    id: 9,
    routeName: "Remera - Downtown",
    routeLength: "5km",
    routeCode: "REM - DOWN",
    busStopsCount: 3,
    assignedBuses: 10,
    startLoc: 6.0,
    destLoc: 24,
    busStops: [
      { id: 1, name: "City Plaza", lat: -1, long: 30 },
      { id: 2, name: "Camp Kigali", lat: -1, long: 30 },
      { id: 3, name: "Kimironko", lat: -1, long: 30 },
    ],
  },
  {
    id: 10,
    routeName: "Remera - Town",
    routeLength: "5km",
    routeCode: "REM - DOWN",
    busStopsCount: 13,
    assignedBuses: 10,
    startLoc: 6.0,
    destLoc: 24,
    busStops: [
      { id: 1, name: "City Plaza", lat: -1, long: 30 },
      { id: 2, name: "Camp Kigali", lat: -1, long: 30 },
      { id: 3, name: "Kimironko", lat: -1, long: 30 },
    ],
  },
  {
    id: 11,
    routeName: "Nyabugogo - Rwandex",
    routeLength: "5km",
    routeCode: "REM - DOWN",
    busStopsCount: 13,
    assignedBuses: 10,
    startLoc: 6.0,
    destLoc: 24,
    busStops: [
      { id: 1, name: "City Plaza", lat: -1, long: 30 },
      { id: 2, name: "Camp Kigali", lat: -1, long: 30 },
      { id: 3, name: "Kimironko", lat: -1, long: 30 },
    ],
  },
  {
    id: 12,
    routeName: "Kacyiru - Kimironko",
    routeLength: "5km",
    routeCode: "REM - DOWN",
    busStopsCount: 13,
    assignedBuses: 10,
    startLoc: 6.0,
    destLoc: 24,
    busStops: [
      { id: 1, name: "City Plaza", lat: -1, long: 30 },
      { id: 2, name: "Camp Kigali", lat: -1, long: 30 },
      { id: 3, name: "Kimironko", lat: -1, long: 30 },
    ],
  },
];

export const busStops = [
  { id: 1, name: "City Plaza", value: "City Plaza", lat: -1, long: 30 },
  { id: 2, name: "Camp Kigali", value: "Camp Kigali", lat: -1, long: 30 },
  { id: 3, name: "Kimironko", value: "Kimironko", lat: -1, long: 30 },
  { id: 4, name: "Onatracom", value: "Onatracom", lat: -1, long: 30 },
  { id: 5, name: "Cosmos", value: "Cosmos", lat: -1, long: 30 },
  { id: 6, name: "CHUK", value: "CHUK", lat: -1, long: 30 },
];

// to be used by material head component "EnhancedTableHead" and for sorting
export const indexNumericSort = 2;
export const indexCharSort = 1;
export const headCells = [
  {
    id: 0,
  },
  {
    id: "routeName",
    numeric: false,
    disablePadding: true,
    label: "Route Name",
  },
  {
    id: "busStopsCount",
    numeric: true,
    disablePadding: false,
    label: "No of Bus Stops",
  },
  {
    id: "assignedBuses",
    numeric: true,
    disablePadding: false,
    label: "Assigned Buses",
  },
  {
    id: "startLoc",
    numeric: true,
    disablePadding: false,
    label: "Start Location",
  },
  {
    id: "destLoc",
    numeric: true,
    disablePadding: false,
    label: "Destination Point",
  },
];
